### ISSUE TITLE
Strings with a number and whitespaces are considered numeric

### ISSUE THREAD

**Issue by vladshcherbin** [miguelmota/is-numeric#2]
Hey, should a string with whitespaces be numeric:

```js
var isNumeric = require('is-numeric')
console.log(isNumeric('   3 ')) // -> true
```

I'd expect it to be false.

**Comment by miguelmota** [comment]
@VladShcherbin 

isNumeric is simply a wrapper around `isNaN` which trims inputs before converting. 

So I added an option to not trim input and return false if it contains whitespace

```js
console.log(isNumeric('   3') // true
console.log(isNumeric('   3', {trim: false}) // false
```

You can npm install the latest release to get the update

**Comment by vladshcherbin** [comment]
@miguelmota

I was fooled by the differences of what is considered `numeric` in different languages. I checked this in php with native `is_numeric` function and the result was `false`. A bit later I came back and checked [this two versions](https://repl.it/repls/WeeInfamousAsianpiedstarling) and remembered how retarded php is 🤦‍♂️

Thanks for `trim` option and sorry for bothering.

**Comment by miguelmota** [comment]
@VladShcherbin php is nuts
